# Site settings
title: Jared's Blog
email: jared@vanessaandjared.com
description: > # this means to ignore newlines until "baseurl:"
  Jared's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jared-moore.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  jared-moore

# Build settings
#highlighter: rouge
markdown: kramdown
